# The name of the organisation
organization = "cct-datascience"

[page]
title = "CCT Data Science FAIR projects dashboard"
header = "FAIR projects dashboard"

[metrics]
description  = true  # Check that the repo has a description
topics       = true  # Check that the repo has keywords
license      = true  # Check that the repo has a license
updated      = true  # Display the last update
cff          = true # Check that the repo is citable with cff file
readme       = true  # Check that the repo has a readme
readability  = true  # Display the readability score for the readme
sections     = ["Contact"] # Check that these sections are in readme

